/* Generated By:JJTree: Do not edit this line. ASTAttributeValuePair.java */

package mediadorxml.javaccparser;

public class ASTAttributeValuePair extends SimpleNode {
  public ASTAttributeValuePair(int id) {
    super(id);
  }

  public ASTAttributeValuePair(XQueryParser p, int id) {
    super(p, id);
  }

}
