/* Generated By:JJTree: Do not edit this line. ASTDecimalLiteral.java */

package mediadorxml.javaccparser;

public class ASTDecimalLiteral extends SimpleNode {
  public ASTDecimalLiteral(int id) {
    super(id);
  }

  public ASTDecimalLiteral(XQueryParser p, int id) {
    super(p, id);
  }

}
