/* Generated By:JJTree: Do not edit this line. ASTElmtContent.java */

package mediadorxml.javaccparser;

public class ASTElmtContent extends SimpleNode {
  public ASTElmtContent(int id) {
    super(id);
  }

  public ASTElmtContent(XQueryParser p, int id) {
    super(p, id);
  }

}
