/* Generated By:JJTree: Do not edit this line. ASTElmtConstructor.java */

package mediadorxml.javaccparser;

public class ASTElmtConstructor extends SimpleNode {
  public ASTElmtConstructor(int id) {
    super(id);
  }

  public ASTElmtConstructor(XQueryParser p, int id) {
    super(p, id);
  }

}
