/* Generated By:JJTree: Do not edit this line. ASTEnclosedExpr.java */

package mediadorxml.javaccparser;

public class ASTEnclosedExpr extends SimpleNode {
  public ASTEnclosedExpr(int id) {
    super(id);
  }

  public ASTEnclosedExpr(XQueryParser p, int id) {
    super(p, id);
  }

}
