/* Generated By:JJTree: Do not edit this line. ASTEquals.java */

package mediadorxml.javaccparser;

public class ASTEquals extends SimpleNode {
  public ASTEquals(int id) {
    super(id);
  }

  public ASTEquals(XQueryParser p, int id) {
    super(p, id);
  }

}
