/* Generated By:JJTree: Do not edit this line. ASTFunctionExpr.java */

package mediadorxml.javaccparser;

public class ASTFunctionExpr extends SimpleNode {
  public ASTFunctionExpr(int id) {
    super(id);
  }

  public ASTFunctionExpr(XQueryParser p, int id) {
    super(p, id);
  }

}
