/* Generated By:JJTree: Do not edit this line. ASTGreaterThan.java */

package mediadorxml.javaccparser;

public class ASTGreaterThan extends SimpleNode {
  public ASTGreaterThan(int id) {
    super(id);
  }

  public ASTGreaterThan(XQueryParser p, int id) {
    super(p, id);
  }

}
