/* Generated By:JJTree: Do not edit this line. ASTLetClause.java */

package mediadorxml.javaccparser;

public class ASTLetClause extends SimpleNode {
  public ASTLetClause(int id) {
    super(id);
  }

  public ASTLetClause(XQueryParser p, int id) {
    super(p, id);
  }

}
