/* Generated By:JJTree: Do not edit this line. ASTNotEquals.java */

package mediadorxml.javaccparser;

public class ASTNotEquals extends SimpleNode {
  public ASTNotEquals(int id) {
    super(id);
  }

  public ASTNotEquals(XQueryParser p, int id) {
    super(p, id);
  }

}
