/* Generated By:JJTree: Do not edit this line. ASTOrderDescending.java */

package mediadorxml.javaccparser;

public class ASTOrderDescending extends SimpleNode {
  public ASTOrderDescending(int id) {
    super(id);
  }

  public ASTOrderDescending(XQueryParser p, int id) {
    super(p, id);
  }

}
