/* Generated By:JJTree: Do not edit this line. ASTOrderSpecList.java */

package mediadorxml.javaccparser;

public class ASTOrderSpecList extends SimpleNode {
  public ASTOrderSpecList(int id) {
    super(id);
  }

  public ASTOrderSpecList(XQueryParser p, int id) {
    super(p, id);
  }

}
