/* Generated By:JJTree: Do not edit this line. ASTOrderByClause.java */

package mediadorxml.javaccparser;

public class ASTOrderByClause extends SimpleNode {
  public ASTOrderByClause(int id) {
    super(id);
  }

  public ASTOrderByClause(XQueryParser p, int id) {
    super(p, id);
  }

}
