/* Generated By:JJTree: Do not edit this line. ASTOrderAscending.java */

package mediadorxml.javaccparser;

public class ASTOrderAscending extends SimpleNode {
  public ASTOrderAscending(int id) {
    super(id);
  }

  public ASTOrderAscending(XQueryParser p, int id) {
    super(p, id);
  }

}
