/* Generated By:JJTree: Do not edit this line. ASTOrExpr.java */

package mediadorxml.javaccparser;

public class ASTOrExpr extends SimpleNode {
  public ASTOrExpr(int id) {
    super(id);
  }

  public ASTOrExpr(XQueryParser p, int id) {
    super(p, id);
  }

}
