/* Generated By:JJTree: Do not edit this line. ASTParenthesizedExpr.java */

package mediadorxml.javaccparser;

public class ASTParenthesizedExpr extends SimpleNode {
  public ASTParenthesizedExpr(int id) {
    super(id);
  }

  public ASTParenthesizedExpr(XQueryParser p, int id) {
    super(p, id);
  }

}
