/* Generated By:JJTree: Do not edit this line. ASTQName.java */

package mediadorxml.javaccparser;

public class ASTQName extends SimpleNode {
  public ASTQName(int id) {
    super(id);
  }

  public ASTQName(XQueryParser p, int id) {
    super(p, id);
  }

}
