/* Generated By:JJTree: Do not edit this line. ASTReturn.java */

package mediadorxml.javaccparser;

public class ASTReturn extends SimpleNode {
  public ASTReturn(int id) {
    super(id);
  }

  public ASTReturn(XQueryParser p, int id) {
    super(p, id);
  }

}
