/* Generated By:JJTree: Do not edit this line. ASTSlash.java */

package mediadorxml.javaccparser;

public class ASTSlash extends SimpleNode {
  public ASTSlash(int id) {
    super(id);
  }

  public ASTSlash(XQueryParser p, int id) {
    super(p, id);
  }

}
