/* Generated By:JJTree: Do not edit this line. ASTStringLiteral.java */

package mediadorxml.javaccparser;

public class ASTStringLiteral extends SimpleNode {
  public ASTStringLiteral(int id) {
    super(id);
  }

  public ASTStringLiteral(XQueryParser p, int id) {
    super(p, id);
  }

}
