/* Generated By:JJTree: Do not edit this line. ASTValueExpr.java */

package mediadorxml.javaccparser;

public class ASTValueExpr extends SimpleNode {
  public ASTValueExpr(int id) {
    super(id);
  }

  public ASTValueExpr(XQueryParser p, int id) {
    super(p, id);
  }

}
