/* Generated By:JJTree: Do not edit this line. ASTVarName.java */

package mediadorxml.javaccparser;

public class ASTVarName extends SimpleNode {
  public ASTVarName(int id) {
    super(id);
  }

  public ASTVarName(XQueryParser p, int id) {
    super(p, id);
  }

}
