package uff.dew.vphadoop.job;

public enum VPCounters {
	NODE0_TOTAL_TIME,
	NODE1_TOTAL_TIME,
	NODE2_TOTAL_TIME,
	NODE3_TOTAL_TIME,
	NODE4_TOTAL_TIME,
	NODE5_TOTAL_TIME,
	NODE6_TOTAL_TIME,
	NODE7_TOTAL_TIME,
	PARTITIONS_WITH_RESULT,
	PREPROCESSING_TIME,
	PROCESSING_TIME,
	COMPOSING_TIME_TOTAL,
	COMPOSING_TIME_LOAD_PARTIALS,
	COMPOSING_TIME_COMBINE_PARTIALS, 
	COMPOSING_TIME_REPOPULATE_OBJECTS
}

