/* Generated By:JJTree: Do not edit this line. ASTAttList.java */

package uff.dew.svp.javaccparser;

public class ASTAttList extends SimpleNode {
  public ASTAttList(int id) {
    super(id);
  }

  public ASTAttList(XQueryParser p, int id) {
    super(p, id);
  }

}
