/* Generated By:JJTree: Do not edit this line. ASTAttValue.java */

package uff.dew.svp.javaccparser;

public class ASTAttValue extends SimpleNode {
  public ASTAttValue(int id) {
    super(id);
  }

  public ASTAttValue(XQueryParser p, int id) {
    super(p, id);
  }

}
