/* Generated By:JJTree: Do not edit this line. ASTAttValueContent.java */

package uff.dew.svp.javaccparser;

public class ASTAttValueContent extends SimpleNode {
  public ASTAttValueContent(int id) {
    super(id);
  }

  public ASTAttValueContent(XQueryParser p, int id) {
    super(p, id);
  }

}
