/* Generated By:JJTree: Do not edit this line. ASTAndExpr.java */

package uff.dew.svp.javaccparser;

public class ASTAndExpr extends SimpleNode {
  public ASTAndExpr(int id) {
    super(id);
  }

  public ASTAndExpr(XQueryParser p, int id) {
    super(p, id);
  }

}
