/* Generated By:JJTree: Do not edit this line. ASTComparisonExpr.java */

package uff.dew.svp.javaccparser;

public class ASTComparisonExpr extends SimpleNode {
  public ASTComparisonExpr(int id) {
    super(id);
  }

  public ASTComparisonExpr(XQueryParser p, int id) {
    super(p, id);
  }

}
