/* Generated By:JJTree: Do not edit this line. ASTDoubleSlash.java */

package uff.dew.svp.javaccparser;

public class ASTDoubleSlash extends SimpleNode {
  public ASTDoubleSlash(int id) {
    super(id);
  }

  public ASTDoubleSlash(XQueryParser p, int id) {
    super(p, id);
  }

}
