/* Generated By:JJTree: Do not edit this line. ASTDoubleLiteral.java */

package uff.dew.svp.javaccparser;

public class ASTDoubleLiteral extends SimpleNode {
  public ASTDoubleLiteral(int id) {
    super(id);
  }

  public ASTDoubleLiteral(XQueryParser p, int id) {
    super(p, id);
  }

}
