/* Generated By:JJTree: Do not edit this line. ASTDocumentExpr.java */

package uff.dew.svp.javaccparser;

public class ASTDocumentExpr extends SimpleNode {
  public ASTDocumentExpr(int id) {
    super(id);
  }

  public ASTDocumentExpr(XQueryParser p, int id) {
    super(p, id);
  }

}
