/* Generated By:JJTree: Do not edit this line. ASTExpr.java */

package uff.dew.svp.javaccparser;

public class ASTExpr extends SimpleNode {
  public ASTExpr(int id) {
    super(id);
  }

  public ASTExpr(XQueryParser p, int id) {
    super(p, id);
  }

}
