/* Generated By:JJTree: Do not edit this line. ASTEndTag.java */

package uff.dew.svp.javaccparser;

public class ASTEndTag extends SimpleNode {
  public ASTEndTag(int id) {
    super(id);
  }

  public ASTEndTag(XQueryParser p, int id) {
    super(p, id);
  }

}
