/* Generated By:JJTree: Do not edit this line. ASTForClause.java */

package uff.dew.svp.javaccparser;

public class ASTForClause extends SimpleNode {
  public ASTForClause(int id) {
    super(id);
  }

  public ASTForClause(XQueryParser p, int id) {
    super(p, id);
  }

}
