/* Generated By:JJTree: Do not edit this line. ASTFuncAverage.java */

package uff.dew.svp.javaccparser;

public class ASTFuncAverage extends SimpleNode {
  public ASTFuncAverage(int id) {
    super(id);
  }

  public ASTFuncAverage(XQueryParser p, int id) {
    super(p, id);
  }

}
