/* Generated By:JJTree: Do not edit this line. ASTFLWORExpr.java */

package uff.dew.svp.javaccparser;

public class ASTFLWORExpr extends SimpleNode {
  public ASTFLWORExpr(int id) {
    super(id);
  }

  public ASTFLWORExpr(XQueryParser p, int id) {
    super(p, id);
  }

}
