/* Generated By:JJTree: Do not edit this line. ASTFuncSum.java */

package uff.dew.svp.javaccparser;

public class ASTFuncSum extends SimpleNode {
  public ASTFuncSum(int id) {
    super(id);
  }

  public ASTFuncSum(XQueryParser p, int id) {
    super(p, id);
  }

}
