/* Generated By:JJTree: Do not edit this line. ASTFuncCount.java */

package uff.dew.svp.javaccparser;

public class ASTFuncCount extends SimpleNode {
  public ASTFuncCount(int id) {
    super(id);
  }

  public ASTFuncCount(XQueryParser p, int id) {
    super(p, id);
  }

}
