/* Generated By:JJTree: Do not edit this line. ASTFuncMax.java */

package uff.dew.svp.javaccparser;

public class ASTFuncMax extends SimpleNode {
  public ASTFuncMax(int id) {
    super(id);
  }

  public ASTFuncMax(XQueryParser p, int id) {
    super(p, id);
  }

}
