/* Generated By:JJTree: Do not edit this line. ASTFuncMin.java */

package uff.dew.svp.javaccparser;

public class ASTFuncMin extends SimpleNode {
  public ASTFuncMin(int id) {
    super(id);
  }

  public ASTFuncMin(XQueryParser p, int id) {
    super(p, id);
  }

}
