/* Generated By:JJTree: Do not edit this line. ASTGreaterThanEquals.java */

package uff.dew.svp.javaccparser;

public class ASTGreaterThanEquals extends SimpleNode {
  public ASTGreaterThanEquals(int id) {
    super(id);
  }

  public ASTGreaterThanEquals(XQueryParser p, int id) {
    super(p, id);
  }

}
