/* Generated By:JJTree: Do not edit this line. ASTGeneralComp.java */

package uff.dew.svp.javaccparser;

public class ASTGeneralComp extends SimpleNode {
  public ASTGeneralComp(int id) {
    super(id);
  }

  public ASTGeneralComp(XQueryParser p, int id) {
    super(p, id);
  }

}
