/* Generated By:JJTree: Do not edit this line. ASTIntegerLiteral.java */

package uff.dew.svp.javaccparser;

public class ASTIntegerLiteral extends SimpleNode {
  public ASTIntegerLiteral(int id) {
    super(id);
  }

  public ASTIntegerLiteral(XQueryParser p, int id) {
    super(p, id);
  }

}
