/* Generated By:JJTree: Do not edit this line. ASTLessThanEquals.java */

package uff.dew.svp.javaccparser;

public class ASTLessThanEquals extends SimpleNode {
  public ASTLessThanEquals(int id) {
    super(id);
  }

  public ASTLessThanEquals(XQueryParser p, int id) {
    super(p, id);
  }

}
