/* Generated By:JJTree: Do not edit this line. ASTLessThan.java */

package uff.dew.svp.javaccparser;

public class ASTLessThan extends SimpleNode {
  public ASTLessThan(int id) {
    super(id);
  }

  public ASTLessThan(XQueryParser p, int id) {
    super(p, id);
  }

}
