/* Generated By:JJTree: Do not edit this line. ASTLiteral.java */

package uff.dew.svp.javaccparser;

public class ASTLiteral extends SimpleNode {
  public ASTLiteral(int id) {
    super(id);
  }

  public ASTLiteral(XQueryParser p, int id) {
    super(p, id);
  }

}
