/* Generated By:JJTree: Do not edit this line. ASTNumericalLiteral.java */

package uff.dew.svp.javaccparser;

public class ASTNumericalLiteral extends SimpleNode {
  public ASTNumericalLiteral(int id) {
    super(id);
  }

  public ASTNumericalLiteral(XQueryParser p, int id) {
    super(p, id);
  }

}
