/* Generated By:JJTree: Do not edit this line. ASTOrderSpec.java */

package uff.dew.svp.javaccparser;

public class ASTOrderSpec extends SimpleNode {
  public ASTOrderSpec(int id) {
    super(id);
  }

  public ASTOrderSpec(XQueryParser p, int id) {
    super(p, id);
  }

}
