/* Generated By:JJTree: Do not edit this line. ASTPathExpr.java */

package uff.dew.svp.javaccparser;

public class ASTPathExpr extends SimpleNode {
  public ASTPathExpr(int id) {
    super(id);
  }

  public ASTPathExpr(XQueryParser p, int id) {
    super(p, id);
  }

}
