/* Generated By:JJTree: Do not edit this line. ASTPrimaryExpr.java */

package uff.dew.svp.javaccparser;

public class ASTPrimaryExpr extends SimpleNode {
  public ASTPrimaryExpr(int id) {
    super(id);
  }

  public ASTPrimaryExpr(XQueryParser p, int id) {
    super(p, id);
  }

}
