/* Generated By:JJTree: Do not edit this line. ASTStart.java */

package uff.dew.svp.javaccparser;

public class ASTStart extends SimpleNode {
  public ASTStart(int id) {
    super(id);
  }

  public ASTStart(XQueryParser p, int id) {
    super(p, id);
  }

}
