/* Generated By:JJTree: Do not edit this line. ASTSimplePathExpr.java */

package uff.dew.svp.javaccparser;

public class ASTSimplePathExpr extends SimpleNode {
  public ASTSimplePathExpr(int id) {
    super(id);
  }

  public ASTSimplePathExpr(XQueryParser p, int id) {
    super(p, id);
  }

}
