/* Generated By:JJTree: Do not edit this line. ASTUnionExpr.java */

package uff.dew.svp.javaccparser;

public class ASTUnionExpr extends SimpleNode {
  public ASTUnionExpr(int id) {
    super(id);
  }

  public ASTUnionExpr(XQueryParser p, int id) {
    super(p, id);
  }

}
