/* Generated By:JJTree: Do not edit this line. ASTWhereClause.java */

package uff.dew.svp.javaccparser;

public class ASTWhereClause extends SimpleNode {
  public ASTWhereClause(int id) {
    super(id);
  }

  public ASTWhereClause(XQueryParser p, int id) {
    super(p, id);
  }

}
