/* Generated By:JJTree&JavaCC: Do not edit this line. XQueryParserConstants.java */
package uff.dew.svp.javaccparser;

public interface XQueryParserConstants {

  int EOF = 0;
  int COMMENT = 5;
  int SEMICOLON = 6;
  int COMMA = 7;
  int EQUALS = 8;
  int L_PAREN = 9;
  int R_PAREN = 10;
  int L_BRACKET = 11;
  int R_BRACKET = 12;
  int L_BRACE = 13;
  int R_BRACE = 14;
  int OR = 15;
  int AND = 16;
  int BAR = 17;
  int UNION = 18;
  int PLUS = 19;
  int MINUS = 20;
  int FOR = 21;
  int LET = 22;
  int WHERE = 23;
  int RETURN = 24;
  int IN = 25;
  int ASSIGN = 26;
  int SLASH = 27;
  int SLASHSLASH = 28;
  int DOLLAR = 29;
  int LESS_THAN = 30;
  int LESS_THAN_SLASH = 31;
  int LESS_THAN_EQUALS = 32;
  int GREATER_THAN = 33;
  int SLASH_GREATER_THAN = 34;
  int GREATER_THAN_EQUALS = 35;
  int NOT_EQUALS = 36;
  int UNDERSCORE = 37;
  int SINGLEQUOTE = 38;
  int QUOTE = 39;
  int DOCUMENT = 40;
  int XML = 41;
  int AT = 42;
  int ASCENDING = 43;
  int DESCENDING = 44;
  int COUNT = 45;
  int MAX = 46;
  int MIN = 47;
  int AVERAGE = 48;
  int SUM = 49;
  int IDENTIFIER = 50;
  int NCNAMECHAR = 51;
  int DIGITS = 52;
  int HEXDIGITS = 53;
  int LETTER = 54;
  int DECIMALLITERAL = 55;
  int DOUBLELITERAL = 56;
  int STRINGLITERAL = 57;
  int CHARREF = 58;
  int PREDEFINEDENTITYREF = 59;
  int BASECHAR = 60;
  int IDEOGRAPHIC = 61;
  int DIGIT = 62;
  int EXTENDER = 63;
  int COMBININGCHAR = 64;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<COMMENT>",
    "\";\"",
    "\",\"",
    "\"=\"",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "\"{\"",
    "\"}\"",
    "<OR>",
    "<AND>",
    "\"|\"",
    "<UNION>",
    "\"+\"",
    "\"-\"",
    "<FOR>",
    "<LET>",
    "<WHERE>",
    "<RETURN>",
    "<IN>",
    "\":=\"",
    "\"/\"",
    "\"//\"",
    "\"$\"",
    "\"<\"",
    "\"</\"",
    "\"<=\"",
    "\">\"",
    "\"/>\"",
    "\">=\"",
    "\"!=\"",
    "\"_\"",
    "\"\\\'\"",
    "\"\\\"\"",
    "<DOCUMENT>",
    "<XML>",
    "\"@\"",
    "<ASCENDING>",
    "<DESCENDING>",
    "<COUNT>",
    "<MAX>",
    "<MIN>",
    "<AVERAGE>",
    "<SUM>",
    "<IDENTIFIER>",
    "<NCNAMECHAR>",
    "<DIGITS>",
    "<HEXDIGITS>",
    "<LETTER>",
    "<DECIMALLITERAL>",
    "<DOUBLELITERAL>",
    "<STRINGLITERAL>",
    "<CHARREF>",
    "<PREDEFINEDENTITYREF>",
    "<BASECHAR>",
    "<IDEOGRAPHIC>",
    "<DIGIT>",
    "<EXTENDER>",
    "<COMBININGCHAR>",
    "\"order by\"",
    "\"ORDER BY\"",
  };

}
